import type { DesignSettings, DisplaySettings } from '../types/widget-config';

export type NotificationTemplateId =
  | 'recent_purchase'
  | 'new_signup'
  | 'customer_review'
  | 'live_visitors'
  | 'form_submission'
  | 'cart_activity'
  | 'active_sessions'
  | 'recent_activity'
  | 'pill_badge';

export interface NotificationDesignPreset {
  id: string;
  templateId: NotificationTemplateId;
  name: string;
  description: string;
  // Only overrides; full config is merged with defaults elsewhere
  design?: Partial<DesignSettings>;
  display?: Partial<DisplaySettings>;
}

export const notificationDesignPresets: NotificationDesignPreset[] = [
  // Recent Purchase
  {
    id: 'recent_purchase_classic_card',
    templateId: 'recent_purchase',
    name: 'Classic Card',
    description: 'Bottom-left glass card with blue accent border.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'card', maxWidth: 320, minWidth: 260 },
      border: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.25)',
        borderStyle: 'solid',
        borderLeftAccent: true,
        borderLeftAccentWidth: 4,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.2)',
        backdropBlur: 18,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#f9fafb',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 8,
        fadeInDuration: 300,
        fadeOutDuration: 300,
        animationType: 'slide',
        progressBar: true,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '• ',
        showLocation: true,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 168,
        showCustomerName: true,
        showRating: true,
        showReviewContent: true,
      },
    },
  },
  {
    id: 'recent_purchase_ripple_bubble',
    templateId: 'recent_purchase',
    name: 'Ripple Bubble',
    description: 'Circular bubble with overlapping avatars, heart badge, and ripple animation.',
    design: {
      position: { position: 'bottom-left', offsetX: 32, offsetY: 32, stackDirection: 'vertical' },
      layout: { layout: 'ripple', maxWidth: 320, minWidth: 200 },
      border: {
        borderRadius: 999,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.5)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#6366F1',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.08)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 5,
        fadeInDuration: 700,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#4F46E5',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: true,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  {
    id: 'recent_purchase_parallax_card',
    templateId: 'recent_purchase',
    name: '3D Parallax Card',
    description: 'Dark 3D card with tilt effect, glossy shine, and floating product image.',
    design: {
      position: { position: 'bottom-right', offsetX: 32, offsetY: 32, stackDirection: 'vertical' },
      layout: { layout: 'parallax', maxWidth: 320, minWidth: 280 },
      border: {
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#6366F1',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.5)',
        backdropBlur: 16,
        glassmorphism: false,
      },
      background: {
        backgroundColor: 'rgba(17, 24, 39, 0.9)',
        backgroundGradient: false,
        gradientStart: '#111827',
        gradientEnd: '#1f2937',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 5,
        fadeInDuration: 700,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#6366F1',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Puzzle Reveal Widget
  {
    id: 'recent_purchase_puzzle',
    templateId: 'recent_purchase',
    name: 'Puzzle Reveal',
    description: 'Three-piece puzzle animation with avatar, message, and product snapping together.',
    design: {
      position: { position: 'bottom-left', offsetX: 32, offsetY: 32, stackDirection: 'vertical' },
      layout: { layout: 'puzzle', maxWidth: 360, minWidth: 280 },
      border: {
        borderRadius: 16,
        borderWidth: 0,
        borderColor: 'transparent',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#6366F1',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.25)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: 'transparent',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 5,
        fadeInDuration: 500,
        fadeOutDuration: 500,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#facc15',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Peekaboo Reveal Widget
  {
    id: 'recent_purchase_peekaboo',
    templateId: 'recent_purchase',
    name: 'Peekaboo Reveal',
    description: 'Playful peek animation from the edge with blinking eye icon and social proof count.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 40, stackDirection: 'vertical' },
      layout: { layout: 'peekaboo', maxWidth: 320, minWidth: 280 },
      border: {
        borderRadius: 24,
        borderWidth: 1,
        borderColor: 'rgba(243, 244, 246, 1)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#6366F1',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 6,
        fadeInDuration: 700,
        fadeOutDuration: 500,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#6366f1',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: 'In the ',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Floating Tag Widget
  {
    id: 'recent_purchase_floating_tag',
    templateId: 'recent_purchase',
    name: 'Floating Tag',
    description: 'Pill-shaped glassmorphic tag that floats gently with subtle animation.',
    design: {
      position: { position: 'bottom-left', offsetX: 0, offsetY: 40, stackDirection: 'vertical' },
      layout: { layout: 'floating-tag', maxWidth: 320, minWidth: 200 },
      border: {
        borderRadius: 50,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.4)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#6366F1',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.05)',
        backdropBlur: 12,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.7)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 4,
        fadeInDuration: 700,
        fadeOutDuration: 500,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#6366f1',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Story Pop Widget
  {
    id: 'recent_purchase_story_pop',
    templateId: 'recent_purchase',
    name: 'Story Pop',
    description: 'Vertical mobile-first widget with CSS micro-animations mimicking video stories.',
    design: {
      position: { position: 'bottom-left', offsetX: 32, offsetY: 32, stackDirection: 'vertical' },
      layout: { layout: 'story-pop', maxWidth: 160, minWidth: 160 },
      border: {
        borderRadius: 16,
        borderWidth: 2,
        borderColor: '#ffffff',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#6366F1',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.25)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 4,
        fadeInDuration: 500,
        fadeOutDuration: 500,
        animationType: 'slide',
        progressBar: true,
        progressBarColor: '#ffffff',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Frosted Token Widget
  {
    id: 'recent_purchase_frosted_token',
    templateId: 'recent_purchase',
    name: 'Frosted Token',
    description: 'Polished glassmorphic token with breathing border animation and gradient icon.',
    design: {
      position: { position: 'bottom-right', offsetX: 40, offsetY: 40, stackDirection: 'vertical' },
      layout: { layout: 'frosted-token', maxWidth: 280, minWidth: 200 },
      border: {
        borderRadius: 50,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#6366F1',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.2)',
        backdropBlur: 12,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 4,
        fadeInDuration: 700,
        fadeOutDuration: 500,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#ffffff',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // New Signup - Classic Card (Default)
  {
    id: 'new_signup_classic_card',
    templateId: 'new_signup',
    name: 'Classic Card',
    description: 'Clean bottom-left card with blue accent border for signups.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'card', maxWidth: 320, minWidth: 260 },
      border: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.25)',
        borderStyle: 'solid',
        borderLeftAccent: true,
        borderLeftAccentWidth: 4,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.2)',
        backdropBlur: 18,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#f9fafb',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 8,
        fadeInDuration: 300,
        fadeOutDuration: 300,
        animationType: 'slide',
        progressBar: true,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '• ',
        showLocation: true,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 48,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // New Signup - Peekaboo
  {
    id: 'new_signup_peekaboo',
    templateId: 'new_signup',
    name: 'Peekaboo Reveal',
    description: 'Playful peek animation with blinking eye that reveals signup details.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'peekaboo', maxWidth: 320, minWidth: 280 },
      border: {
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#ffffff',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.25)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 6,
        fadeInDuration: 400,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: true,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: false,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 48,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // New Signup - 3D Parallax
  {
    id: 'new_signup_parallax',
    templateId: 'new_signup',
    name: '3D Parallax Card',
    description: 'Interactive 3D card with mouse-tracking parallax tilt effect.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'parallax', maxWidth: 320, minWidth: 280 },
      border: {
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.3)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: true,
        gradientStart: '#3B82F6',
        gradientEnd: '#8B5CF6',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 6,
        fadeInDuration: 400,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: true,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: false,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 48,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Customer Review - Classic Card (Default)
  {
    id: 'customer_review_classic_card',
    templateId: 'customer_review',
    name: 'Classic Card',
    description: 'Clean bottom-left card with yellow accent border for reviews.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'card', maxWidth: 340, minWidth: 260 },
      border: {
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(250, 204, 21, 0.35)',
        borderStyle: 'solid',
        borderLeftAccent: true,
        borderLeftAccentWidth: 3,
        borderLeftAccentColor: '#FACC15',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'md',
        shadowColor: 'rgba(15, 23, 42, 0.2)',
        backdropBlur: 12,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#fefce8',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 9,
        fadeInDuration: 280,
        fadeOutDuration: 280,
        animationType: 'slide',
        progressBar: true,
        progressBarColor: '#FACC15',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 168,
        showCustomerName: true,
        showRating: true,
        showReviewContent: true,
      },
    },
  },

  // Customer Review - Peekaboo
  {
    id: 'customer_review_peekaboo',
    templateId: 'customer_review',
    name: 'Peekaboo Reveal',
    description: 'Playful peek animation with blinking eye that reveals customer review.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'peekaboo', maxWidth: 340, minWidth: 280 },
      border: {
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#ffffff',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#FACC15',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.25)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 8,
        fadeInDuration: 400,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#FACC15',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: false,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 168,
        showCustomerName: true,
        showRating: true,
        showReviewContent: true,
      },
    },
  },

  // Customer Review - 3D Parallax
  {
    id: 'customer_review_parallax',
    templateId: 'customer_review',
    name: '3D Parallax Card',
    description: 'Interactive 3D card with mouse-tracking parallax tilt effect for reviews.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'parallax', maxWidth: 340, minWidth: 280 },
      border: {
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#FACC15',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.3)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: true,
        gradientStart: '#FACC15',
        gradientEnd: '#F59E0B',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 8,
        fadeInDuration: 400,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#FACC15',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: false,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 168,
        showCustomerName: true,
        showRating: true,
        showReviewContent: true,
      },
    },
  },

  // Live Visitors - Classic Card (Default)
  {
    id: 'live_visitors_classic_card',
    templateId: 'live_visitors',
    name: 'Classic Card',
    description: 'Clean bottom-left card with blue accent border for live visitors.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'card', maxWidth: 320, minWidth: 260 },
      border: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.25)',
        borderStyle: 'solid',
        borderLeftAccent: true,
        borderLeftAccentWidth: 4,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.2)',
        backdropBlur: 18,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#f9fafb',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 0,
        fadeInDuration: 300,
        fadeOutDuration: 300,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 1,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Live Visitors - Peekaboo
  {
    id: 'live_visitors_peekaboo',
    templateId: 'live_visitors',
    name: 'Peekaboo Reveal',
    description: 'Playful peek animation with blinking eye showing live visitor count.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'peekaboo', maxWidth: 320, minWidth: 280 },
      border: {
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#ffffff',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#22C55E',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.25)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 0,
        fadeInDuration: 400,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#22C55E',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 1,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Live Visitors - 3D Parallax
  {
    id: 'live_visitors_parallax',
    templateId: 'live_visitors',
    name: '3D Parallax Card',
    description: 'Interactive 3D card with mouse-tracking parallax tilt effect showing live visitors.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'parallax', maxWidth: 320, minWidth: 280 },
      border: {
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#22C55E',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.3)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: true,
        gradientStart: '#22C55E',
        gradientEnd: '#10B981',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 0,
        fadeInDuration: 400,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#22C55E',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 1,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Live Visitors - Floating Tag
  {
    id: 'live_visitors_floating_tag',
    templateId: 'live_visitors',
    name: 'Floating Tag',
    description: 'Glassmorphic floating pill with breathing animation showing live visitors.',
    design: {
      position: { position: 'bottom-right', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'floating-tag', maxWidth: 280, minWidth: 200 },
      border: {
        borderRadius: 50,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.4)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#22C55E',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.05)',
        backdropBlur: 12,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.7)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 0,
        fadeInDuration: 700,
        fadeOutDuration: 500,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#22C55E',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 1,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Live Visitors - Frosted Token
  {
    id: 'live_visitors_frosted_token',
    templateId: 'live_visitors',
    name: 'Frosted Token',
    description: 'Polished glassmorphic token with breathing border animation showing live visitors.',
    design: {
      position: { position: 'bottom-right', offsetX: 40, offsetY: 40, stackDirection: 'vertical' },
      layout: { layout: 'frosted-token', maxWidth: 280, minWidth: 200 },
      border: {
        borderRadius: 50,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#22C55E',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.2)',
        backdropBlur: 12,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 0,
        fadeInDuration: 700,
        fadeOutDuration: 500,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#22C55E',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 1,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Form Submission - Classic Card (Default)
  {
    id: 'form_submission_classic_card',
    templateId: 'form_submission',
    name: 'Classic Card',
    description: 'Clean bottom-left card with blue accent border for form submissions.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'card', maxWidth: 320, minWidth: 260 },
      border: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.25)',
        borderStyle: 'solid',
        borderLeftAccent: true,
        borderLeftAccentWidth: 4,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.2)',
        backdropBlur: 18,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#f9fafb',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 8,
        fadeInDuration: 300,
        fadeOutDuration: 300,
        animationType: 'slide',
        progressBar: true,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '• ',
        showLocation: true,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 168,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Form Submission
  {
    id: 'form_submission_card_bottom_right',
    templateId: 'form_submission',
    name: 'Form Submission Card',
    description: 'Bottom-right confirmation card for new form submissions.',
    design: {
      position: { position: 'bottom-right', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'card', maxWidth: 340, minWidth: 260 },
      border: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.25)',
        borderStyle: 'solid',
        borderLeftAccent: true,
        borderLeftAccentWidth: 3,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'md',
        shadowColor: 'rgba(15, 23, 42, 0.22)',
        backdropBlur: 10,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#eff6ff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 7,
        fadeInDuration: 260,
        fadeOutDuration: 260,
        animationType: 'slide',
        progressBar: true,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 168,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Form Submission - Peekaboo
  {
    id: 'form_submission_peekaboo',
    templateId: 'form_submission',
    name: 'Peekaboo Reveal',
    description: 'Playful peek animation with blinking eye that reveals form submission details.',
    design: {
      position: { position: 'bottom-right', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'peekaboo', maxWidth: 320, minWidth: 280 },
      border: {
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#ffffff',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.25)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 6,
        fadeInDuration: 400,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 168,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Form Submission - 3D Parallax
  {
    id: 'form_submission_parallax',
    templateId: 'form_submission',
    name: '3D Parallax Card',
    description: 'Interactive 3D card with mouse-tracking parallax tilt effect for form submissions.',
    design: {
      position: { position: 'bottom-right', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'parallax', maxWidth: 320, minWidth: 280 },
      border: {
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.3)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: true,
        gradientStart: '#3B82F6',
        gradientEnd: '#06B6D4',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 6,
        fadeInDuration: 400,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 168,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Cart Activity - Classic Card (Default)
  {
    id: 'cart_activity_classic_card',
    templateId: 'cart_activity',
    name: 'Classic Card',
    description: 'Clean bottom-left card with blue accent border for cart activity.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'card', maxWidth: 320, minWidth: 260 },
      border: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.25)',
        borderStyle: 'solid',
        borderLeftAccent: true,
        borderLeftAccentWidth: 4,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.2)',
        backdropBlur: 18,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#f9fafb',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 8,
        fadeInDuration: 300,
        fadeOutDuration: 300,
        animationType: 'slide',
        progressBar: true,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '• ',
        showLocation: true,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Cart Activity
  {
    id: 'cart_activity_bottom_left',
    templateId: 'cart_activity',
    name: 'Cart Activity Badge',
    description: 'Bottom-left card showing cart activity and urgency.',
    design: {
      position: { position: 'bottom-left', offsetX: 22, offsetY: 22, stackDirection: 'vertical' },
      layout: { layout: 'compact', maxWidth: 320, minWidth: 260 },
      border: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(248, 113, 113, 0.35)',
        borderStyle: 'solid',
        borderLeftAccent: true,
        borderLeftAccentWidth: 3,
        borderLeftAccentColor: '#F97316',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'md',
        shadowColor: 'rgba(15, 23, 42, 0.22)',
        backdropBlur: 10,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.96)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#fff7ed',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 8,
        fadeInDuration: 260,
        fadeOutDuration: 260,
        animationType: 'slide',
        progressBar: true,
        progressBarColor: '#F97316',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Cart Activity - Ripple
  {
    id: 'cart_activity_ripple',
    templateId: 'cart_activity',
    name: 'Ripple Bubble',
    description: 'Overlapping circular avatars with expanding ripple animation for cart activity.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'ripple', maxWidth: 300, minWidth: 260 },
      border: {
        borderRadius: 50,
        borderWidth: 2,
        borderColor: '#ffffff',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#F97316',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.15)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 6,
        fadeInDuration: 300,
        fadeOutDuration: 300,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#F97316',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Cart Activity - Puzzle
  {
    id: 'cart_activity_puzzle',
    templateId: 'cart_activity',
    name: 'Puzzle Reveal',
    description: 'Animated puzzle pieces that assemble to reveal cart activity.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'puzzle', maxWidth: 320, minWidth: 280 },
      border: {
        borderRadius: 16,
        borderWidth: 2,
        borderColor: '#ffffff',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#F97316',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.25)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: true,
        gradientStart: '#F97316',
        gradientEnd: '#EF4444',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 7,
        fadeInDuration: 400,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#F97316',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Active Sessions - Classic Card (Default)
  {
    id: 'active_sessions_classic_card',
    templateId: 'active_sessions',
    name: 'Classic Card',
    description: 'Clean bottom-left card with blue accent border for active sessions.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'card', maxWidth: 320, minWidth: 260 },
      border: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.25)',
        borderStyle: 'solid',
        borderLeftAccent: true,
        borderLeftAccentWidth: 4,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.2)',
        backdropBlur: 18,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#f9fafb',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 0,
        fadeInDuration: 300,
        fadeOutDuration: 300,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 1,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Active Sessions
  {
    id: 'active_sessions_top_left',
    templateId: 'active_sessions',
    name: 'Active Sessions Label',
    description: 'Small label at top-left showing active sessions.',
    design: {
      position: { position: 'top-left', offsetX: 16, offsetY: 16, stackDirection: 'vertical' },
      layout: { layout: 'compact', maxWidth: 260, minWidth: 200 },
      border: {
        borderRadius: 999,
        borderWidth: 0,
        borderColor: 'transparent',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'sm',
        shadowColor: 'rgba(15, 23, 42, 0.22)',
        backdropBlur: 14,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(15, 23, 42, 0.82)',
        backgroundGradient: true,
        gradientStart: '#0f172a',
        gradientEnd: '#1e293b',
        gradientDirection: 'to-r',
      },
    },
    display: {
      duration: {
        displayDuration: 0,
        fadeInDuration: 220,
        fadeOutDuration: 220,
        animationType: 'fade',
        progressBar: false,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 1,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Active Sessions - Floating Tag
  {
    id: 'active_sessions_floating_tag',
    templateId: 'active_sessions',
    name: 'Floating Tag',
    description: 'Glassmorphic floating pill with breathing animation showing active sessions.',
    design: {
      position: { position: 'top-right', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'floating-tag', maxWidth: 280, minWidth: 200 },
      border: {
        borderRadius: 50,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.4)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.05)',
        backdropBlur: 12,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.7)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 0,
        fadeInDuration: 700,
        fadeOutDuration: 500,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 1,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Active Sessions - Frosted Token
  {
    id: 'active_sessions_frosted_token',
    templateId: 'active_sessions',
    name: 'Frosted Token',
    description: 'Polished glassmorphic token with breathing border animation showing active sessions.',
    design: {
      position: { position: 'top-right', offsetX: 40, offsetY: 40, stackDirection: 'vertical' },
      layout: { layout: 'frosted-token', maxWidth: 280, minWidth: 200 },
      border: {
        borderRadius: 50,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.2)',
        backdropBlur: 12,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 0,
        fadeInDuration: 700,
        fadeOutDuration: 500,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 1,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Recent Activity - Classic Card (Default)
  {
    id: 'recent_activity_classic_card',
    templateId: 'recent_activity',
    name: 'Classic Card',
    description: 'Clean bottom-left card with blue accent border for recent activity.',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'card', maxWidth: 320, minWidth: 260 },
      border: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.25)',
        borderStyle: 'solid',
        borderLeftAccent: true,
        borderLeftAccentWidth: 4,
        borderLeftAccentColor: '#3B82F6',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.2)',
        backdropBlur: 18,
        glassmorphism: true,
      },
      background: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#f9fafb',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 8,
        fadeInDuration: 300,
        fadeOutDuration: 300,
        animationType: 'slide',
        progressBar: true,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: true,
        timestampFormat: 'relative',
        timestampPrefix: '• ',
        showLocation: true,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 168,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Recent Activity - Ripple Bubble
  {
    id: 'recent_activity_ripple_bubble',
    templateId: 'recent_activity',
    name: 'Ripple Bubble',
    description: 'Circular bubble with overlapping avatars and ripple animation for recent activity.',
    design: {
      position: { position: 'bottom-left', offsetX: 32, offsetY: 32, stackDirection: 'vertical' },
      layout: { layout: 'ripple', maxWidth: 320, minWidth: 200 },
      border: {
        borderRadius: 999,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.5)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#6366F1',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'lg',
        shadowColor: 'rgba(0, 0, 0, 0.08)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 5,
        fadeInDuration: 700,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#4F46E5',
        progressBarPosition: 'top',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: true,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Recent Activity - 3D Parallax Card
  {
    id: 'recent_activity_parallax_card',
    templateId: 'recent_activity',
    name: '3D Parallax Card',
    description: 'Dark 3D card with tilt effect and glossy shine for recent activity.',
    design: {
      position: { position: 'bottom-right', offsetX: 32, offsetY: 32, stackDirection: 'vertical' },
      layout: { layout: 'parallax', maxWidth: 320, minWidth: 280 },
      border: {
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: '#6366F1',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'xl',
        shadowColor: 'rgba(0, 0, 0, 0.5)',
        backdropBlur: 16,
        glassmorphism: false,
      },
      background: {
        backgroundColor: 'rgba(17, 24, 39, 0.9)',
        backgroundGradient: false,
        gradientStart: '#111827',
        gradientEnd: '#1f2937',
        gradientDirection: 'to-br',
      },
    },
    display: {
      duration: {
        displayDuration: 5,
        fadeInDuration: 700,
        fadeOutDuration: 400,
        animationType: 'slide',
        progressBar: false,
        progressBarColor: '#6366F1',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: true,
        showEventIcon: true,
        showValue: false,
        valueFormat: 'currency',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: true,
        showRating: false,
        showReviewContent: false,
      },
    },
  },

  // Pill Badge - Daily Stats
  {
    id: 'pill_badge_visitors',
    templateId: 'pill_badge',
    name: 'Visitors Today',
    description: 'Compact pill showing today\'s visitor count',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'pill-badge', maxWidth: 200, minWidth: 120 },
      border: {
        borderRadius: 50,
        borderWidth: 1,
        borderColor: 'rgba(229, 231, 235, 1)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: 'transparent',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'sm',
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-r',
      },
    },
    display: {
      duration: {
        displayDuration: 8, // 8 seconds like other widgets
        fadeInDuration: 500,
        fadeOutDuration: 300,
        animationType: 'fade',
        progressBar: false,
        progressBarColor: '#3B82F6',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
        useCustomFormMessage: false,
        customFormMessage: '',
      },
    },
  },
  {
    id: 'pill_badge_purchases',
    templateId: 'pill_badge',
    name: 'Purchases Today',
    description: 'Compact pill showing today\'s purchase count',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'pill-badge', maxWidth: 200, minWidth: 120 },
      border: {
        borderRadius: 50,
        borderWidth: 1,
        borderColor: 'rgba(229, 231, 235, 1)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: 'transparent',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'sm',
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-r',
      },
    },
    display: {
      duration: {
        displayDuration: 8, // 8 seconds like other widgets
        fadeInDuration: 500,
        fadeOutDuration: 300,
        animationType: 'fade',
        progressBar: false,
        progressBarColor: '#10B981',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
        useCustomFormMessage: false,
        customFormMessage: '',
      },
    },
  },
  {
    id: 'pill_badge_reviews',
    templateId: 'pill_badge',
    name: 'Reviews Today',
    description: 'Compact pill showing today\'s review count',
    design: {
      position: { position: 'bottom-left', offsetX: 24, offsetY: 24, stackDirection: 'vertical' },
      layout: { layout: 'pill-badge', maxWidth: 200, minWidth: 120 },
      border: {
        borderRadius: 50,
        borderWidth: 1,
        borderColor: 'rgba(229, 231, 235, 1)',
        borderStyle: 'solid',
        borderLeftAccent: false,
        borderLeftAccentWidth: 0,
        borderLeftAccentColor: 'transparent',
      },
      shadow: {
        shadowEnabled: true,
        shadowSize: 'sm',
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        backdropBlur: 0,
        glassmorphism: false,
      },
      background: {
        backgroundColor: '#ffffff',
        backgroundGradient: false,
        gradientStart: '#ffffff',
        gradientEnd: '#ffffff',
        gradientDirection: 'to-r',
      },
    },
    display: {
      duration: {
        displayDuration: 8, // 8 seconds like other widgets
        fadeInDuration: 500,
        fadeOutDuration: 300,
        animationType: 'fade',
        progressBar: false,
        progressBarColor: '#F59E0B',
        progressBarPosition: 'bottom',
      },
      content: {
        showTimestamp: false,
        timestampFormat: 'relative',
        timestampPrefix: '',
        showLocation: false,
        locationFormat: 'city',
        showUserAvatar: false,
        showEventIcon: true,
        showValue: true,
        valueFormat: 'number',
        currency: 'USD',
        currencyPosition: 'before',
        notificationTimeRange: 24,
        showCustomerName: false,
        showRating: false,
        showReviewContent: false,
        useCustomFormMessage: false,
        customFormMessage: '',
      },
    },
  },

];
